name: Rust
on:
  push:
    branches: [ main, hotfix/*, feature/* ]
  pull_request:
    branches: [ main, release/* ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - uses: Swatinem/rust-cache@v1
    - name: Build
      run: |
        sudo apt-get update
        cargo clippy --tests -- -D warnings
    - name: Run tests
      env:
        RUST_BACKTRACE: FULL
      run: |
        sudo apt-get update
        cargo test -- --test-threads=1 --nocapture
        